//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutDialogButtonCancel {
            get {
                return ResourceManager.GetString("AboutDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2012-2017 Pylyp Lebediev.
        /// </summary>
        public static string AboutDialogCompanyName {
            get {
                return ResourceManager.GetString("AboutDialogCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database version.
        /// </summary>
        public static string AboutDialogDataBaseVersion {
            get {
                return ResourceManager.GetString("AboutDialogDataBaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed to Dent Life.
        /// </summary>
        public static string AboutDialogLicense {
            get {
                return ResourceManager.GetString("AboutDialogLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutDialogMainLabel {
            get {
                return ResourceManager.GetString("AboutDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dental Soft.
        /// </summary>
        public static string AboutDialogSoftName {
            get {
                return ResourceManager.GetString("AboutDialogSoftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutDialogVersion {
            get {
                return ResourceManager.GetString("AboutDialogVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows: {0}.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows:.
        /// </summary>
        public static string AmountNotFormatted {
            get {
                return ResourceManager.GetString("AmountNotFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add appointment.
        /// </summary>
        public static string AppointmentAddItemTitle {
            get {
                return ResourceManager.GetString("AppointmentAddItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider to change time of the current appointment..
        /// </summary>
        public static string AppointmentChangeTime {
            get {
                return ResourceManager.GetString("AppointmentChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end time of an appointment has to be different!.
        /// </summary>
        public static string AppointmentStartEndTimeMustBeDifferent {
            get {
                return ResourceManager.GetString("AppointmentStartEndTimeMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time of an appointment has to be less than end time!.
        /// </summary>
        public static string AppointmentStartTimeMustBeLessEndTime {
            get {
                return ResourceManager.GetString("AppointmentStartTimeMustBeLessEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment in the same range of time already exists!.
        /// </summary>
        public static string AppointmentWithSameTimeExists {
            get {
                return ResourceManager.GetString("AppointmentWithSameTimeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are run under Client mode. Scheduled database
        ///backup will not be run from this computer.
        /// </summary>
        public static string BackupLogsClientMode {
            get {
                return ResourceManager.GetString("BackupLogsClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string BackupLogsDialogBackupTypesName {
            get {
                return ResourceManager.GetString("BackupLogsDialogBackupTypesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string BackupLogsDialogEndDateTime {
            get {
                return ResourceManager.GetString("BackupLogsDialogEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string BackupLogsDialogFileName {
            get {
                return ResourceManager.GetString("BackupLogsDialogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started by.
        /// </summary>
        public static string BackupLogsDialogNameStartedBy {
            get {
                return ResourceManager.GetString("BackupLogsDialogNameStartedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string BackupLogsDialogStartDateTime {
            get {
                return ResourceManager.GetString("BackupLogsDialogStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string BackupLogsDialogStatus {
            get {
                return ResourceManager.GetString("BackupLogsDialogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an appointment.
        /// </summary>
        public static string ButtonAddAppointment {
            get {
                return ResourceManager.GetString("ButtonAddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add institution.
        /// </summary>
        public static string ButtonAddEducation {
            get {
                return ResourceManager.GetString("ButtonAddEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string ButtonAddLogin {
            get {
                return ResourceManager.GetString("ButtonAddLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add notification.
        /// </summary>
        public static string ButtonAddNotificationGroup {
            get {
                return ResourceManager.GetString("ButtonAddNotificationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add template.
        /// </summary>
        public static string ButtonAddNotificationTemplate {
            get {
                return ResourceManager.GetString("ButtonAddNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add patient.
        /// </summary>
        public static string ButtonAddPatient {
            get {
                return ResourceManager.GetString("ButtonAddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add position.
        /// </summary>
        public static string ButtonAddPosition {
            get {
                return ResourceManager.GetString("ButtonAddPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add reminder.
        /// </summary>
        public static string ButtonAddReminder {
            get {
                return ResourceManager.GetString("ButtonAddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add staff.
        /// </summary>
        public static string ButtonAddStaff {
            get {
                return ResourceManager.GetString("ButtonAddStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete institution.
        /// </summary>
        public static string ButtonDeleteEducation {
            get {
                return ResourceManager.GetString("ButtonDeleteEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import invalid email addresses.
        /// </summary>
        public static string ButtonDeleteInValidateEmails {
            get {
                return ResourceManager.GetString("ButtonDeleteInValidateEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string ButtonDeleteLogin {
            get {
                return ResourceManager.GetString("ButtonDeleteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete notification.
        /// </summary>
        public static string ButtonDeleteNotificationGroup {
            get {
                return ResourceManager.GetString("ButtonDeleteNotificationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete template.
        /// </summary>
        public static string ButtonDeleteNotificationTemplate {
            get {
                return ResourceManager.GetString("ButtonDeleteNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete patient.
        /// </summary>
        public static string ButtonDeletePatient {
            get {
                return ResourceManager.GetString("ButtonDeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete position.
        /// </summary>
        public static string ButtonDeletePosition {
            get {
                return ResourceManager.GetString("ButtonDeletePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete reminder.
        /// </summary>
        public static string ButtonDeleteReminder {
            get {
                return ResourceManager.GetString("ButtonDeleteReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete staff.
        /// </summary>
        public static string ButtonDeleteStaff {
            get {
                return ResourceManager.GetString("ButtonDeleteStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit institution.
        /// </summary>
        public static string ButtonEditEducation {
            get {
                return ResourceManager.GetString("ButtonEditEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string ButtonEditLogin {
            get {
                return ResourceManager.GetString("ButtonEditLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit notification.
        /// </summary>
        public static string ButtonEditNotificationGroup {
            get {
                return ResourceManager.GetString("ButtonEditNotificationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit template.
        /// </summary>
        public static string ButtonEditNotificationTemplate {
            get {
                return ResourceManager.GetString("ButtonEditNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit patient.
        /// </summary>
        public static string ButtonEditPatient {
            get {
                return ResourceManager.GetString("ButtonEditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit position.
        /// </summary>
        public static string ButtonEditPosition {
            get {
                return ResourceManager.GetString("ButtonEditPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit reminder.
        /// </summary>
        public static string ButtonEditReminder {
            get {
                return ResourceManager.GetString("ButtonEditReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit staff.
        /// </summary>
        public static string ButtonEditStaff {
            get {
                return ResourceManager.GetString("ButtonEditStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ButtonRefreshBackup {
            get {
                return ResourceManager.GetString("ButtonRefreshBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register backup.
        /// </summary>
        public static string ButtonRunBackup {
            get {
                return ResourceManager.GetString("ButtonRunBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select doctor.
        /// </summary>
        public static string ButtonSelectAppointmentDoctor {
            get {
                return ResourceManager.GetString("ButtonSelectAppointmentDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is on.
        /// </summary>
        public static string CapsLockOn {
            get {
                return ResourceManager.GetString("CapsLockOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EducationDialogButtonCancel {
            get {
                return ResourceManager.GetString("EducationDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EducationDialogButtonSave {
            get {
                return ResourceManager.GetString("EducationDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational institution.
        /// </summary>
        public static string EducationDialogMainInfo {
            get {
                return ResourceManager.GetString("EducationDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational institution.
        /// </summary>
        public static string EducationDialogMainLabel {
            get {
                return ResourceManager.GetString("EducationDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EducationDialogName {
            get {
                return ResourceManager.GetString("EducationDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string EducationDialogShortName {
            get {
                return ResourceManager.GetString("EducationDialogShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email addresses.
        /// </summary>
        public static string FilterPatientWithInvalidEmails {
            get {
                return ResourceManager.GetString("FilterPatientWithInvalidEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterReminder {
            get {
                return ResourceManager.GetString("FilterReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LoginDialogButtonCancel {
            get {
                return ResourceManager.GetString("LoginDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string LoginDialogButtonLogin {
            get {
                return ResourceManager.GetString("LoginDialogButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can login.
        /// </summary>
        public static string LoginDialogIsCanLogin {
            get {
                return ResourceManager.GetString("LoginDialogIsCanLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LoginDialogLogin {
            get {
                return ResourceManager.GetString("LoginDialogLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LoginDialogLoginName {
            get {
                return ResourceManager.GetString("LoginDialogLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please try again.
        /// </summary>
        public static string LoginDialogLogonFailed {
            get {
                return ResourceManager.GetString("LoginDialogLogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, application is loading....
        /// </summary>
        public static string LoginDialogLogonSucceeded {
            get {
                return ResourceManager.GetString("LoginDialogLogonSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s information.
        /// </summary>
        public static string LoginDialogMainInfo {
            get {
                return ResourceManager.GetString("LoginDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LoginDialogMainLabel {
            get {
                return ResourceManager.GetString("LoginDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginDialogPassword {
            get {
                return ResourceManager.GetString("LoginDialogPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Password protected&gt;.
        /// </summary>
        public static string LoginDialogPasswordProtection {
            get {
                return ResourceManager.GetString("LoginDialogPasswordProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string LoginDialogPasswordRepeat {
            get {
                return ResourceManager.GetString("LoginDialogPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role in system.
        /// </summary>
        public static string LoginDialogRoleInSystem {
            get {
                return ResourceManager.GetString("LoginDialogRoleInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string LoginDialogRoleName {
            get {
                return ResourceManager.GetString("LoginDialogRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string LoginDialogStaff {
            get {
                return ResourceManager.GetString("LoginDialogStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance to the program.
        /// </summary>
        public static string LoginDialogTitle {
            get {
                return ResourceManager.GetString("LoginDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Dental Soft.
        /// </summary>
        public static string LoginDialogWelcome {
            get {
                return ResourceManager.GetString("LoginDialogWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dental Soft.
        /// </summary>
        public static string MainFormHeader {
            get {
                return ResourceManager.GetString("MainFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of email addresses that has/ve been invalidated is/are {0}..
        /// </summary>
        public static string MessageBoxAmountOfEmailHaveBeenInvalidated {
            get {
                return ResourceManager.GetString("MessageBoxAmountOfEmailHaveBeenInvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import invalid email addresses.
        /// </summary>
        public static string MessageBoxAmountOfEmailHaveBeenInvalidatedHeader {
            get {
                return ResourceManager.GetString("MessageBoxAmountOfEmailHaveBeenInvalidatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the email addresses has been invalidated..
        /// </summary>
        public static string MessageBoxAmountOfEmailHaveBeenInvalidatedIsNull {
            get {
                return ResourceManager.GetString("MessageBoxAmountOfEmailHaveBeenInvalidatedIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected record?.
        /// </summary>
        public static string MessageBoxDeleteConfirmation {
            get {
                return ResourceManager.GetString("MessageBoxDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record.
        /// </summary>
        public static string MessageBoxDeleteHeader {
            get {
                return ResourceManager.GetString("MessageBoxDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will not be saved, since group was processed or is being processed..
        /// </summary>
        public static string MessageBoxNotificationListCannotBeSaved {
            get {
                return ResourceManager.GetString("MessageBoxNotificationListCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save record.
        /// </summary>
        public static string MessageBoxNotificationListCannotBeSavedHeader {
            get {
                return ResourceManager.GetString("MessageBoxNotificationListCannotBeSavedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group has to be saved before you start working with notification list. Are you sure you want to save this group?.
        /// </summary>
        public static string MessageBoxSaveGroupConfirmation {
            get {
                return ResourceManager.GetString("MessageBoxSaveGroupConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save record.
        /// </summary>
        public static string MessageBoxSaveGroupHeader {
            get {
                return ResourceManager.GetString("MessageBoxSaveGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during the saving changes..
        /// </summary>
        public static string MessageBoxSavingFailed {
            get {
                return ResourceManager.GetString("MessageBoxSavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save record.
        /// </summary>
        public static string MessageBoxSavingFailedHeader {
            get {
                return ResourceManager.GetString("MessageBoxSavingFailedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the backup file isn&apos;t valid. Settings cannot be saved..
        /// </summary>
        public static string MessageBoxSettingsCannotBeSaved {
            get {
                return ResourceManager.GetString("MessageBoxSettingsCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MessageBoxSettingsCannotBeSavedHeader {
            get {
                return ResourceManager.GetString("MessageBoxSettingsCannotBeSavedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected record cannot be deleted. Maybe this record in use in another tables..
        /// </summary>
        public static string MessageBoxTheEntryCannotBeDeleted {
            get {
                return ResourceManager.GetString("MessageBoxTheEntryCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavigationAbout {
            get {
                return ResourceManager.GetString("NavigationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string NavigationAppointment {
            get {
                return ResourceManager.GetString("NavigationAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup.
        /// </summary>
        public static string NavigationBackup {
            get {
                return ResourceManager.GetString("NavigationBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational institution.
        /// </summary>
        public static string NavigationEducation {
            get {
                return ResourceManager.GetString("NavigationEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string NavigationLogin {
            get {
                return ResourceManager.GetString("NavigationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        public static string NavigationNotificationGroup {
            get {
                return ResourceManager.GetString("NavigationNotificationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string NavigationNotificationTemplate {
            get {
                return ResourceManager.GetString("NavigationNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string NavigationPatient {
            get {
                return ResourceManager.GetString("NavigationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string NavigationPosition {
            get {
                return ResourceManager.GetString("NavigationPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string NavigationReminder {
            get {
                return ResourceManager.GetString("NavigationReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavigationSetting {
            get {
                return ResourceManager.GetString("NavigationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string NavigationStaff {
            get {
                return ResourceManager.GetString("NavigationStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close .
        /// </summary>
        public static string NotificationClose {
            get {
                return ResourceManager.GetString("NotificationClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor: .
        /// </summary>
        public static string NotificationDoctor {
            get {
                return ResourceManager.GetString("NotificationDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. Message to {0} ({1}) has been sent successfully at {2}..
        /// </summary>
        public static string NotificationEmailSuccessfulResult {
            get {
                return ResourceManager.GetString("NotificationEmailSuccessfulResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel current delivery?.
        /// </summary>
        public static string NotificationGroupCancelDeliveryConfirmation {
            get {
                return ResourceManager.GetString("NotificationGroupCancelDeliveryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel delivery.
        /// </summary>
        public static string NotificationGroupCancelDeliveryHeader {
            get {
                return ResourceManager.GetString("NotificationGroupCancelDeliveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group processing has been canceled..
        /// </summary>
        public static string NotificationGroupCancelled {
            get {
                return ResourceManager.GetString("NotificationGroupCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current group cannot be deleted since email delivery has been started..
        /// </summary>
        public static string NotificationGroupCannotBeDeleted {
            get {
                return ResourceManager.GetString("NotificationGroupCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are run under Client mode. Email notifications        ///will not be send from this computer.
        /// </summary>
        public static string NotificationGroupClientMode {
            get {
                return ResourceManager.GetString("NotificationGroupClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NotificationGroupDescription {
            get {
                return ResourceManager.GetString("NotificationGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NotificationGroupDialogButtonCancel {
            get {
                return ResourceManager.GetString("NotificationGroupDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel delivery.
        /// </summary>
        public static string NotificationGroupDialogButtonCancelDelivery {
            get {
                return ResourceManager.GetString("NotificationGroupDialogButtonCancelDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart delivery.
        /// </summary>
        public static string NotificationGroupDialogButtonRestartDelivery {
            get {
                return ResourceManager.GetString("NotificationGroupDialogButtonRestartDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart delivery for failed.
        /// </summary>
        public static string NotificationGroupDialogButtonRestartDeliveryForFailed {
            get {
                return ResourceManager.GetString("NotificationGroupDialogButtonRestartDeliveryForFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NotificationGroupDialogButtonSave {
            get {
                return ResourceManager.GetString("NotificationGroupDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select receivers....
        /// </summary>
        public static string NotificationGroupDialogButtonSelect {
            get {
                return ResourceManager.GetString("NotificationGroupDialogButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View email statuses....
        /// </summary>
        public static string NotificationGroupDialogButtonStart {
            get {
                return ResourceManager.GetString("NotificationGroupDialogButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NotificationGroupDialogDescription {
            get {
                return ResourceManager.GetString("NotificationGroupDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string NotificationGroupDialogEndDate {
            get {
                return ResourceManager.GetString("NotificationGroupDialogEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notification information.
        /// </summary>
        public static string NotificationGroupDialogMainInfo {
            get {
                return ResourceManager.GetString("NotificationGroupDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notification.
        /// </summary>
        public static string NotificationGroupDialogMainLabel {
            get {
                return ResourceManager.GetString("NotificationGroupDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string NotificationGroupDialogStartDate {
            get {
                return ResourceManager.GetString("NotificationGroupDialogStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string NotificationGroupDialogStatus {
            get {
                return ResourceManager.GetString("NotificationGroupDialogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string NotificationGroupDialogTemplate {
            get {
                return ResourceManager.GetString("NotificationGroupDialogTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group hasn&apos;t been processed..
        /// </summary>
        public static string NotificationGroupNotProcessed {
            get {
                return ResourceManager.GetString("NotificationGroupNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group was processed {0}..
        /// </summary>
        public static string NotificationGroupProcessed {
            get {
                return ResourceManager.GetString("NotificationGroupProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group is processing..
        /// </summary>
        public static string NotificationGroupProcessing {
            get {
                return ResourceManager.GetString("NotificationGroupProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string NotificationGroupStartDate {
            get {
                return ResourceManager.GetString("NotificationGroupStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string NotificationGroupStartTime {
            get {
                return ResourceManager.GetString("NotificationGroupStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string NotificationGroupTemplate {
            get {
                return ResourceManager.GetString("NotificationGroupTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of the email addresses separated by Enter.
        /// </summary>
        public static string NotificationInValidateEmailViewDialogAddresses {
            get {
                return ResourceManager.GetString("NotificationInValidateEmailViewDialogAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NotificationInValidateEmailViewDialogButtonCancel {
            get {
                return ResourceManager.GetString("NotificationInValidateEmailViewDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string NotificationInValidateEmailViewDialogButtonImport {
            get {
                return ResourceManager.GetString("NotificationInValidateEmailViewDialogButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses.
        /// </summary>
        public static string NotificationInValidateEmailViewDialogMainInfo {
            get {
                return ResourceManager.GetString("NotificationInValidateEmailViewDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import invalid email addresses.
        /// </summary>
        public static string NotificationInValidateEmailViewDialogMainLabel {
            get {
                return ResourceManager.GetString("NotificationInValidateEmailViewDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string NotificationListDialogButtonCancel {
            get {
                return ResourceManager.GetString("NotificationListDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string NotificationListDialogButtonRefresh {
            get {
                return ResourceManager.GetString("NotificationListDialogButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NotificationListDialogButtonSave {
            get {
                return ResourceManager.GetString("NotificationListDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NotificationListDialogCancelFilter {
            get {
                return ResourceManager.GetString("NotificationListDialogCancelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string NotificationListDialogEmail {
            get {
                return ResourceManager.GetString("NotificationListDialogEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string NotificationListDialogError {
            get {
                return ResourceManager.GetString("NotificationListDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string NotificationListDialogFilter {
            get {
                return ResourceManager.GetString("NotificationListDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery list.
        /// </summary>
        public static string NotificationListDialogMainLabel {
            get {
                return ResourceManager.GetString("NotificationListDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string NotificationListDialogPatient {
            get {
                return ResourceManager.GetString("NotificationListDialogPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send date.
        /// </summary>
        public static string NotificationListDialogSendDate {
            get {
                return ResourceManager.GetString("NotificationListDialogSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string NotificationListDialogStatus {
            get {
                return ResourceManager.GetString("NotificationListDialogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NotificationListManageDialogButtonCancel {
            get {
                return ResourceManager.GetString("NotificationListManageDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NotificationListManageDialogButtonSave {
            get {
                return ResourceManager.GetString("NotificationListManageDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NotificationListManageDialogCancelFilter {
            get {
                return ResourceManager.GetString("NotificationListManageDialogCancelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string NotificationListManageDialogEmail {
            get {
                return ResourceManager.GetString("NotificationListManageDialogEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string NotificationListManageDialogFilter {
            get {
                return ResourceManager.GetString("NotificationListManageDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery list.
        /// </summary>
        public static string NotificationListManageDialogMainLabel {
            get {
                return ResourceManager.GetString("NotificationListManageDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string NotificationListManageDialogReceiver {
            get {
                return ResourceManager.GetString("NotificationListManageDialogReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NotificationNext {
            get {
                return ResourceManager.GetString("NotificationNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient: .
        /// </summary>
        public static string NotificationPatient {
            get {
                return ResourceManager.GetString("NotificationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string NotificationPrevious {
            get {
                return ResourceManager.GetString("NotificationPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current template cannot be deleted since it in use in group for which email delivery has been started..
        /// </summary>
        public static string NotificationTemplateCannotBeDeleted {
            get {
                return ResourceManager.GetString("NotificationTemplateCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string NotificationTemplateDialogBody {
            get {
                return ResourceManager.GetString("NotificationTemplateDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NotificationTemplateDialogButtonCancel {
            get {
                return ResourceManager.GetString("NotificationTemplateDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NotificationTemplateDialogButtonSave {
            get {
                return ResourceManager.GetString("NotificationTemplateDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NotificationTemplateDialogDescription {
            get {
                return ResourceManager.GetString("NotificationTemplateDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template&apos;s information.
        /// </summary>
        public static string NotificationTemplateDialogMainInfo {
            get {
                return ResourceManager.GetString("NotificationTemplateDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NotificationTemplateDialogTitle {
            get {
                return ResourceManager.GetString("NotificationTemplateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string NotificationTemplateMainLabel {
            get {
                return ResourceManager.GetString("NotificationTemplateMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about the patient.
        /// </summary>
        public static string PatientDialogAdditionalInfo {
            get {
                return ResourceManager.GetString("PatientDialogAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PatientDialogAddress {
            get {
                return ResourceManager.GetString("PatientDialogAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string PatientDialogBirthday {
            get {
                return ResourceManager.GetString("PatientDialogBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PatientDialogButtonCancel {
            get {
                return ResourceManager.GetString("PatientDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PatientDialogButtonSave {
            get {
                return ResourceManager.GetString("PatientDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string PatientDialogComments {
            get {
                return ResourceManager.GetString("PatientDialogComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete photo.
        /// </summary>
        public static string PatientDialogDeletePhoto {
            get {
                return ResourceManager.GetString("PatientDialogDeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PatientDialogEmail {
            get {
                return ResourceManager.GetString("PatientDialogEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string PatientDialogFirstName {
            get {
                return ResourceManager.GetString("PatientDialogFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is checked.
        /// </summary>
        public static string PatientDialogIsEmailChecked {
            get {
                return ResourceManager.GetString("PatientDialogIsEmailChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notification is allowed.
        /// </summary>
        public static string PatientDialogIsEmailNotificationAllowed {
            get {
                return ResourceManager.GetString("PatientDialogIsEmailNotificationAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string PatientDialogJob {
            get {
                return ResourceManager.GetString("PatientDialogJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main information about the patient.
        /// </summary>
        public static string PatientDialogMainInfo {
            get {
                return ResourceManager.GetString("PatientDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string PatientDialogMainLabel {
            get {
                return ResourceManager.GetString("PatientDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit patient.
        /// </summary>
        public static string PatientDialogMainLabelEdit {
            get {
                return ResourceManager.GetString("PatientDialogMainLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View information.
        /// </summary>
        public static string PatientDialogMainLabelView {
            get {
                return ResourceManager.GetString("PatientDialogMainLabelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string PatientDialogMiddleName {
            get {
                return ResourceManager.GetString("PatientDialogMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        public static string PatientDialogPhoneNumberCell {
            get {
                return ResourceManager.GetString("PatientDialogPhoneNumberCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        public static string PatientDialogPhoneNumberHome {
            get {
                return ResourceManager.GetString("PatientDialogPhoneNumberHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work phone.
        /// </summary>
        public static string PatientDialogPhoneNumberWork {
            get {
                return ResourceManager.GetString("PatientDialogPhoneNumberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string PatientDialogPhoto {
            get {
                return ResourceManager.GetString("PatientDialogPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading photo..
        /// </summary>
        public static string PatientDialogPhotoUploadErrorText {
            get {
                return ResourceManager.GetString("PatientDialogPhotoUploadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo upload.
        /// </summary>
        public static string PatientDialogPhotoUploadErrorTitle {
            get {
                return ResourceManager.GetString("PatientDialogPhotoUploadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string PatientDialogProfession {
            get {
                return ResourceManager.GetString("PatientDialogProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo....
        /// </summary>
        public static string PatientDialogSelectImage {
            get {
                return ResourceManager.GetString("PatientDialogSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string PatientDialogSex {
            get {
                return ResourceManager.GetString("PatientDialogSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string PatientDialogSurname {
            get {
                return ResourceManager.GetString("PatientDialogSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture....
        /// </summary>
        public static string PatientDialogTakePicture {
            get {
                return ResourceManager.GetString("PatientDialogTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PositionDialogButtonCancel {
            get {
                return ResourceManager.GetString("PositionDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PositionDialogButtonSave {
            get {
                return ResourceManager.GetString("PositionDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attending.
        /// </summary>
        public static string PositionDialogIsAttending {
            get {
                return ResourceManager.GetString("PositionDialogIsAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position information.
        /// </summary>
        public static string PositionDialogMainInfo {
            get {
                return ResourceManager.GetString("PositionDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionDialogMainLabel {
            get {
                return ResourceManager.GetString("PositionDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position name.
        /// </summary>
        public static string PositionDialogName {
            get {
                return ResourceManager.GetString("PositionDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        public static string PreviewDialogTakePicture {
            get {
                return ResourceManager.GetString("PreviewDialogTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ReminderDate {
            get {
                return ResourceManager.GetString("ReminderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ReminderDialogButtonCancel {
            get {
                return ResourceManager.GetString("ReminderDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ReminderDialogButtonSave {
            get {
                return ResourceManager.GetString("ReminderDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ReminderDialogDate {
            get {
                return ResourceManager.GetString("ReminderDialogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string ReminderDialogDoctor {
            get {
                return ResourceManager.GetString("ReminderDialogDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder information.
        /// </summary>
        public static string ReminderDialogMainInfo {
            get {
                return ResourceManager.GetString("ReminderDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string ReminderDialogMainLabel {
            get {
                return ResourceManager.GetString("ReminderDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ReminderDialogMessage {
            get {
                return ResourceManager.GetString("ReminderDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string ReminderDialogPatient {
            get {
                return ResourceManager.GetString("ReminderDialogPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string ReminderDoctor {
            get {
                return ResourceManager.GetString("ReminderDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not set.
        /// </summary>
        public static string ReminderDoctorWasNotSelected {
            get {
                return ResourceManager.GetString("ReminderDoctorWasNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string ReminderIsCompleted {
            get {
                return ResourceManager.GetString("ReminderIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ReminderMessage {
            get {
                return ResourceManager.GetString("ReminderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the doctor.
        /// </summary>
        public static string ReminderSelectDoctor {
            get {
                return ResourceManager.GetString("ReminderSelectDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string RemindertAlert {
            get {
                return ResourceManager.GetString("RemindertAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string RemindertComment {
            get {
                return ResourceManager.GetString("RemindertComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ReminderTime {
            get {
                return ResourceManager.GetString("ReminderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string RemindertPatient {
            get {
                return ResourceManager.GetString("RemindertPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel search.
        /// </summary>
        public static string SearchCancel {
            get {
                return ResourceManager.GetString("SearchCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchExpression {
            get {
                return ResourceManager.GetString("SearchExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By first letters.
        /// </summary>
        public static string SearchPatientByFirstCharts {
            get {
                return ResourceManager.GetString("SearchPatientByFirstCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Delivery.
        /// </summary>
        public static string SettingDialoEmailDeliveryTab {
            get {
                return ResourceManager.GetString("SettingDialoEmailDeliveryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the backuped database.
        /// </summary>
        public static string SettingDialogBackupDatabaseName {
            get {
                return ResourceManager.GetString("SettingDialogBackupDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the backup file.
        /// </summary>
        public static string SettingDialogBackupFileName {
            get {
                return ResourceManager.GetString("SettingDialogBackupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string SettingDialogBackupInfo {
            get {
                return ResourceManager.GetString("SettingDialogBackupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the backup file (on database server).
        /// </summary>
        public static string SettingDialogBackupLocation {
            get {
                return ResourceManager.GetString("SettingDialogBackupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of the backup.
        /// </summary>
        public static string SettingDialogBackupTime {
            get {
                return ResourceManager.GetString("SettingDialogBackupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingDialogButtonCancel {
            get {
                return ResourceManager.GetString("SettingDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingDialogButtonSave {
            get {
                return ResourceManager.GetString("SettingDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP settings.
        /// </summary>
        public static string SettingDialogEmalsInfo {
            get {
                return ResourceManager.GetString("SettingDialogEmalsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string SettingDialoGeneralTab {
            get {
                return ResourceManager.GetString("SettingDialoGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingDialogLanguage {
            get {
                return ResourceManager.GetString("SettingDialogLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingDialogLanguageInfo {
            get {
                return ResourceManager.GetString("SettingDialogLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingDialogMainLabel {
            get {
                return ResourceManager.GetString("SettingDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify every (minutes).
        /// </summary>
        public static string SettingDialogNotification {
            get {
                return ResourceManager.GetString("SettingDialogNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string SettingDialogNotificationInfo {
            get {
                return ResourceManager.GetString("SettingDialogNotificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to reload the program after changing the language of the user interface.
        /// </summary>
        public static string SettingDialogNotificationToRestart {
            get {
                return ResourceManager.GetString("SettingDialogNotificationToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string SettingDialogSmtpFromAddress {
            get {
                return ResourceManager.GetString("SettingDialogSmtpFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SettingDialogSmtpHost {
            get {
                return ResourceManager.GetString("SettingDialogSmtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SettingDialogSmtpPassword {
            get {
                return ResourceManager.GetString("SettingDialogSmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SettingDialogSmtpPort {
            get {
                return ResourceManager.GetString("SettingDialogSmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string SettingDialogSmtpUserName {
            get {
                return ResourceManager.GetString("SettingDialogSmtpUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video devices Settings.
        /// </summary>
        public static string SettingDialogVideoDevicesInfo {
            get {
                return ResourceManager.GetString("SettingDialogVideoDevicesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of the video devices.
        /// </summary>
        public static string SettingDialogVideoDevicesList {
            get {
                return ResourceManager.GetString("SettingDialogVideoDevicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Devices.
        /// </summary>
        public static string SettingDialogVideoDevicesTab {
            get {
                return ResourceManager.GetString("SettingDialogVideoDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL.
        /// </summary>
        public static string SettingSmtpEnableSsl {
            get {
                return ResourceManager.GetString("SettingSmtpEnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information about the staff.
        /// </summary>
        public static string StaffDialogAdditionalInfo {
            get {
                return ResourceManager.GetString("StaffDialogAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string StaffDialogAddress {
            get {
                return ResourceManager.GetString("StaffDialogAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string StaffDialogBirthday {
            get {
                return ResourceManager.GetString("StaffDialogBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StaffDialogButtonCancel {
            get {
                return ResourceManager.GetString("StaffDialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string StaffDialogButtonSave {
            get {
                return ResourceManager.GetString("StaffDialogButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string StaffDialogComments {
            get {
                return ResourceManager.GetString("StaffDialogComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string StaffDialogEducation {
            get {
                return ResourceManager.GetString("StaffDialogEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string StaffDialogEmail {
            get {
                return ResourceManager.GetString("StaffDialogEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string StaffDialogFirstName {
            get {
                return ResourceManager.GetString("StaffDialogFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conducts the admission of patients.
        /// </summary>
        public static string StaffDialogIsTaking {
            get {
                return ResourceManager.GetString("StaffDialogIsTaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main information about the staff.
        /// </summary>
        public static string StaffDialogMainInfo {
            get {
                return ResourceManager.GetString("StaffDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string StaffDialogMainLabel {
            get {
                return ResourceManager.GetString("StaffDialogMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string StaffDialogMiddleName {
            get {
                return ResourceManager.GetString("StaffDialogMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        public static string StaffDialogPhoneNumberCell {
            get {
                return ResourceManager.GetString("StaffDialogPhoneNumberCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        public static string StaffDialogPhoneNumberHome {
            get {
                return ResourceManager.GetString("StaffDialogPhoneNumberHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work phone.
        /// </summary>
        public static string StaffDialogPhoneNumberWork {
            get {
                return ResourceManager.GetString("StaffDialogPhoneNumberWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string StaffDialogPosition {
            get {
                return ResourceManager.GetString("StaffDialogPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string StaffDialogSex {
            get {
                return ResourceManager.GetString("StaffDialogSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string StaffDialogSurname {
            get {
                return ResourceManager.GetString("StaffDialogSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StyledMessageBoxButtonCancel {
            get {
                return ResourceManager.GetString("StyledMessageBoxButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string StyledMessageBoxButtonNo {
            get {
                return ResourceManager.GetString("StyledMessageBoxButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string StyledMessageBoxButtonOk {
            get {
                return ResourceManager.GetString("StyledMessageBoxButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string StyledMessageBoxButtonYes {
            get {
                return ResourceManager.GetString("StyledMessageBoxButtonYes", resourceCulture);
            }
        }
    }
}
