//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddAppointmentAdd {
            get {
                return ResourceManager.GetString("AddAppointmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddAppointmentClose {
            get {
                return ResourceManager.GetString("AddAppointmentClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string AddAppointmentComment {
            get {
                return ResourceManager.GetString("AddAppointmentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string AddAppointmentDoctor {
            get {
                return ResourceManager.GetString("AddAppointmentDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment end time.
        /// </summary>
        public static string AddAppointmentEndTime {
            get {
                return ResourceManager.GetString("AddAppointmentEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string AddAppointmentPatient {
            get {
                return ResourceManager.GetString("AddAppointmentPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date.
        /// </summary>
        public static string AddAppointmentSelectDate {
            get {
                return ResourceManager.GetString("AddAppointmentSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment start time.
        /// </summary>
        public static string AddAppointmentStartTime {
            get {
                return ResourceManager.GetString("AddAppointmentStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string AddAppointmentTitle {
            get {
                return ResourceManager.GetString("AddAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment information.
        /// </summary>
        public static string AppointmentDialogMainInfo {
            get {
                return ResourceManager.GetString("AppointmentDialogMainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new appointment.
        /// </summary>
        public static string CalendarAddItemDescription {
            get {
                return ResourceManager.GetString("CalendarAddItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add appointment.
        /// </summary>
        public static string CalendarAddItemTitle {
            get {
                return ResourceManager.GetString("CalendarAddItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to delete current appointment.
        /// </summary>
        public static string CalendarDeleteItemDescription {
            get {
                return ResourceManager.GetString("CalendarDeleteItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the appointment.
        /// </summary>
        public static string CalendarDeleteItemTitle {
            get {
                return ResourceManager.GetString("CalendarDeleteItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit current appointment.
        /// </summary>
        public static string CalendarEditItemDescription {
            get {
                return ResourceManager.GetString("CalendarEditItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit an appointment.
        /// </summary>
        public static string CalendarEditItemTitle {
            get {
                return ResourceManager.GetString("CalendarEditItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go to the next day.
        /// </summary>
        public static string CalendarNextDayDescription {
            get {
                return ResourceManager.GetString("CalendarNextDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next day.
        /// </summary>
        public static string CalendarNextDayTitle {
            get {
                return ResourceManager.GetString("CalendarNextDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go to the previous day.
        /// </summary>
        public static string CalendarPreviousDayDescription {
            get {
                return ResourceManager.GetString("CalendarPreviousDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous day.
        /// </summary>
        public static string CalendarPreviousDayTitle {
            get {
                return ResourceManager.GetString("CalendarPreviousDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected day.
        /// </summary>
        public static string CalendarSelectedDayDescription {
            get {
                return ResourceManager.GetString("CalendarSelectedDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected day.
        /// </summary>
        public static string CalendarSelectedDayTitle {
            get {
                return ResourceManager.GetString("CalendarSelectedDayTitle", resourceCulture);
            }
        }
    }
}
